# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: stgerard <stgerard@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/12/08 19:06:31 by stgerard          #+#    #+#              #
#    Updated: 2022/12/12 14:24:39 by stgerard         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = minishell

CC = gcc

CFLAGS = -Wall -Wextra -Werror -g

RM = rm -f

SRCS = minishell.c utls.c \
../libft/ft_putstr.c ../libft/ft_split.c ../libft/ft_strlen.c \
../libft/ft_strdup.c

OBJS = ${SRCS:.c=.o}

all: ${NAME}

${NAME}: ${OBJ}
			${CC} -lreadline ${OBJ} ${CFLAGS} -o ${NAME}

clean:
			${RM} ${OBJS}

fclean: clean
			${RM} ${NAME}

re: fclean all

.PHONY: all clean fclean re