version: "3.7"
    
services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build: ./requirements/mariadb
    env_file:
    - ./.env
    volumes:
      - ~/data/mariadb:/var/lib/mysql
    expose:
      - "3306"
    restart: unless-stopped

  nginx:
    container_name: nginx
    networks:
      - inception
    build: ./requirements/nginx
    env_file:
    - ./.env
    depends_on:
      - wordpress
    volumes:
      - ~/data/wordpress:/var/www
    ports:
      - "8080:8080" 		# on indique le port qui sera exposé a la machine locale
    restart: unless-stopped 		# Ici nous changeons, le container redémarrera uniquement en cas de crash.

  wordpress:
    container_name: wordpress
    networks:
      - inception
    build: ./requirements/wordpress
    env_file:
    - ./.env
    depends_on:    					# WordPress démarrera uniquement après MariaDB (sinon il ne pourra pas configurer la base de données...)
      - mariadb
    volumes:
      - ~/data/wordpress:/var/www
    expose:
      - "9000"
    restart: unless-stopped

networks:
  inception:
    driver: bridge

# pour build:   docker-compose up <-f> <path_docker_compose> -d --build // precise le chemin si pas dans le dossier
# pour l'arreter:   docker-compose -f  <path_docker_compose> stop
# pour supprimer le build:  docker-compose -f  <path_docker_compose> down -v
# pour supprimer tous les comtainer:  docker system prune -af
# RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone 
