version: "3"
    
services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build: ./requirements/mariadb
    env_file:
    - ./.env
    volumes:
      - /home/stgerard/data/mariadb:/var/lib/mysql
    expose:
      - "3306"
    restart: unless-stopped

  nginx:
    container_name: nginx
    networks:
      - inception
    build: ./requirements/nginx
    env_file:
    - ./.env
    depends_on:
      - wordpress
    volumes:
      - /home/stgerard/data/wordpress:/var/www/wordpress
    ports:
      - "443:443" # on indique le port qui sera exposé a la machine locale
    restart: unless-stopped # Ici nous changeons, le container redémarrera uniquement en cas de crash.

  wordpress:
    container_name: wordpress
    networks:
      - inception
    build: ./requirements/wordpress
    env_file:
    - ./.env
    depends_on:
      - mariadb
    volumes:
      - /home/stgerard/data/wordpress:/var/www/wordpress
    expose:
      - "9000"
    restart: unless-stopped

networks:
  inception:
    driver: bridge

