FROM debian:buster

# docker build -t nginx .    // builr en donnant un nom en ETANT DANS LE BON DOSSIER
# docker image ls            // voir l'image lance si le build est reussi
# docker run -it nginx      // run l'image
# docker ps                 // connaitre les docker lance

EXPOSE 443
